name: Trivy

on:
  workflow_dispatch:

jobs:
  trivy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Scan code for vulnerabilities
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: false
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: 0
##          output: trivy-report.json
##
##      - name: Print Trivy JSON
##        run: cat trivy-report.json
##
##      - name: Convert Trivy JSON to HTML
##        run: |
##          python3 -m pip install --upgrade pip
##          python3 .github/scripts/trivy_to_html.py
##
##      - name: Print generated HTML
##        run: cat email-body.html

##      - name: Send email via SendGrid
##        env:
##          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
##          TO_EMAIL: protari@amsoft-group.com
##          FROM_EMAIL: vpascari@amsoft-group.com
##        run: |
##          echo "Reading scan report..."
##          REPORT_CONTENT=$(cat trivy-report.txt | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
##
##          cat <<EOF > sendgrid_payload.json
##          {
##            "personalizations": [{
##              "to": [{ "email": "${TO_EMAIL}" }]
##            }],
##            "from": { "email": "${FROM_EMAIL}" },
##            "subject": "Trivy Scan Report",
##            "content": [{
##              "type": "text/html",
##              "value": "$(cat email-body.html | sed 's/"/\\"/g' | tr -d '\n')"
##            }]
##          }
##          EOF
##
##          curl --request POST \
##          --url https://api.sendgrid.com/v3/mail/send \
##          --header "Authorization: Bearer $SENDGRID_API_KEY" \
##          --header 'Content-Type: application/json' \
##          --data @sendgrid_payload.json